import type { LevelDef } from './schema';

const FOUR_FRUITS = ['mango', 'orange', 'grape', 'watermelon'] as const;
const FIVE_FRUITS = [...FOUR_FRUITS, 'mangosteen'] as const;

// 7x7 with corners nipped off — the first shaped (non-rectangular) board.
const CORNERS_CUT_7 = ['X.....X', '.......', '.......', '.......', '.......', '.......', 'X.....X'];

const JELLY_DIAMOND_7 = ['...J...', '..JJJ..', '.JJJJJ.', 'JJJJJJJ', '.JJJJJ.', '..JJJ..', '...J...'];

const JELLY_BLOCK_8 = [
  '........',
  '........',
  '..JJJJ..',
  '..JJJJ..',
  '..JJJJ..',
  '..JJJJ..',
  '........',
  '........',
];

const CORNERS_CUT_8 = [
  'X......X',
  '........',
  '........',
  '........',
  '........',
  '........',
  '........',
  'X......X',
];

export const LEVELS_13_30: LevelDef[] = [
  {
    id: 13,
    width: 7,
    height: 7,
    layout: CORNERS_CUT_7,
    fruits: [...FOUR_FRUITS],
    moves: 22,
    objective: { type: 'collect', fruit: 'grape', count: 20 },
    starScores: [900, 1500],
  },
  {
    id: 14,
    width: 7,
    height: 7,
    fruits: [...FOUR_FRUITS],
    moves: 20,
    objective: { type: 'score', target: 1400 },
    starScores: [2100, 3200],
  },
  {
    id: 15,
    width: 7,
    height: 7,
    layout: JELLY_DIAMOND_7,
    fruits: [...FOUR_FRUITS],
    moves: 24,
    objective: { type: 'jelly' },
    starScores: [1600, 2600],
  },
  {
    id: 16,
    width: 7,
    height: 7,
    fruits: [...FIVE_FRUITS],
    moves: 22,
    objective: { type: 'collect', fruit: 'mangosteen', count: 18 },
    starScores: [900, 1500],
  },
  {
    id: 17,
    width: 7,
    height: 7,
    fruits: [...FIVE_FRUITS],
    moves: 20,
    objective: { type: 'score', target: 1500 },
    starScores: [2200, 3400],
  },
  {
    id: 18,
    width: 7,
    height: 7,
    layout: CORNERS_CUT_7,
    fruits: [...FIVE_FRUITS],
    moves: 24,
    objective: { type: 'collect', fruit: 'orange', count: 22 },
    starScores: [1000, 1700],
  },
  {
    id: 19,
    width: 7,
    height: 7,
    layout: JELLY_DIAMOND_7,
    fruits: [...FIVE_FRUITS],
    moves: 26,
    objective: { type: 'jelly' },
    starScores: [1700, 2800],
  },
  {
    id: 20,
    width: 7,
    height: 7,
    fruits: [...FIVE_FRUITS],
    moves: 22,
    objective: { type: 'score', target: 1600 },
    starScores: [2400, 3600],
  },
  {
    id: 21,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 26,
    objective: { type: 'collect', fruit: 'mango', count: 26 },
    starScores: [1100, 1800],
  },
  {
    id: 22,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 24,
    objective: { type: 'score', target: 1700 },
    starScores: [2500, 3800],
  },
  {
    id: 23,
    width: 8,
    height: 8,
    layout: JELLY_BLOCK_8,
    fruits: [...FIVE_FRUITS],
    moves: 28,
    objective: { type: 'jelly' },
    starScores: [1900, 3000],
  },
  {
    id: 24,
    width: 8,
    height: 8,
    layout: CORNERS_CUT_8,
    fruits: [...FIVE_FRUITS],
    moves: 26,
    objective: { type: 'collect', fruit: 'watermelon', count: 28 },
    starScores: [1200, 2000],
  },
  {
    id: 25,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 24,
    objective: { type: 'score', target: 1800 },
    starScores: [2700, 4000],
  },
  {
    id: 26,
    width: 7,
    height: 7,
    // Fewer fruit kinds makes a 5-in-a-row (a color bomb) much easier to
    // land — this level exists to hand the player their first color bomb.
    fruits: [...FOUR_FRUITS],
    moves: 22,
    objective: { type: 'score', target: 1600 },
    starScores: [2400, 3600],
  },
  {
    id: 27,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 26,
    objective: { type: 'collect', fruit: 'grape', count: 30 },
    starScores: [1300, 2100],
  },
  {
    id: 28,
    width: 8,
    height: 8,
    layout: JELLY_BLOCK_8,
    fruits: [...FIVE_FRUITS],
    moves: 30,
    objective: { type: 'jelly' },
    starScores: [2000, 3200],
  },
  {
    id: 29,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 24,
    objective: { type: 'score', target: 1900 },
    starScores: [2800, 4200],
  },
  {
    id: 30,
    width: 8,
    height: 8,
    layout: CORNERS_CUT_8,
    fruits: [...FIVE_FRUITS],
    moves: 28,
    objective: { type: 'collect', fruit: 'mangosteen', count: 30 },
    starScores: [1300, 2200],
  },
];
