import type { LevelDef } from './schema';

const FIVE_FRUITS = ['mango', 'orange', 'grape', 'watermelon', 'mangosteen'] as const;
const SIX_FRUITS = [...FIVE_FRUITS, 'banana'] as const;

const JELLY_RING_8 = [
  '........',
  '.JJJJJJ.',
  '.J....J.',
  '.J....J.',
  '.J....J.',
  '.J....J.',
  '.JJJJJJ.',
  '........',
];

const JELLY_CROSS_8 = [
  '...JJ...',
  '...JJ...',
  '..JJJJ..',
  'JJJJJJJJ',
  'JJJJJJJJ',
  '..JJJJ..',
  '...JJ...',
  '...JJ...',
];

const DIAMOND_HOLES_8 = [
  'XX....XX',
  'X......X',
  '........',
  '........',
  '........',
  '........',
  'X......X',
  'XX....XX',
];

const JELLY_RING_HOLES_8 = [
  'X......X',
  '.JJJJJJ.',
  '.J....J.',
  '.J....J.',
  '.J....J.',
  '.J....J.',
  '.JJJJJJ.',
  'X......X',
];

export const LEVELS_31_48: LevelDef[] = [
  {
    id: 31,
    width: 8,
    height: 8,
    // Sixth fruit joins the mix — a little easier while it settles in.
    fruits: [...SIX_FRUITS],
    moves: 30,
    objective: { type: 'collect', fruit: 'banana', count: 24 },
    starScores: [1100, 1800],
  },
  {
    id: 32,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 24,
    objective: { type: 'score', target: 2000 },
    starScores: [3000, 4400],
  },
  {
    id: 33,
    width: 8,
    height: 8,
    layout: JELLY_RING_8,
    fruits: [...SIX_FRUITS],
    moves: 30,
    objective: { type: 'jelly' },
    starScores: [2100, 3300],
  },
  {
    id: 34,
    width: 8,
    height: 8,
    layout: DIAMOND_HOLES_8,
    fruits: [...SIX_FRUITS],
    moves: 28,
    objective: { type: 'collect', fruit: 'mango', count: 28 },
    starScores: [1300, 2100],
  },
  {
    id: 35,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 24,
    objective: { type: 'score', target: 2100 },
    starScores: [3100, 4600],
  },
  {
    id: 36,
    width: 8,
    height: 8,
    layout: JELLY_CROSS_8,
    fruits: [...SIX_FRUITS],
    moves: 32,
    objective: { type: 'jelly' },
    starScores: [2300, 3600],
  },
  {
    id: 37,
    width: 8,
    height: 8,
    fruits: [...SIX_FRUITS],
    moves: 30,
    objective: { type: 'collect', fruit: 'orange', count: 30 },
    starScores: [1400, 2300],
  },
  {
    id: 38,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 26,
    objective: { type: 'score', target: 2200 },
    starScores: [3200, 4800],
  },
  {
    id: 39,
    width: 8,
    height: 8,
    layout: JELLY_RING_HOLES_8,
    fruits: [...SIX_FRUITS],
    moves: 32,
    objective: { type: 'jelly' },
    starScores: [2400, 3700],
  },
  {
    id: 40,
    width: 8,
    height: 8,
    fruits: [...SIX_FRUITS],
    moves: 30,
    objective: { type: 'collect', fruit: 'grape', count: 30 },
    starScores: [1400, 2300],
  },
  {
    id: 41,
    width: 8,
    height: 8,
    fruits: [...FIVE_FRUITS],
    moves: 26,
    objective: { type: 'score', target: 2300 },
    starScores: [3300, 5000],
  },
  {
    id: 42,
    width: 8,
    height: 8,
    layout: JELLY_CROSS_8,
    fruits: [...SIX_FRUITS],
    moves: 34,
    objective: { type: 'jelly' },
    starScores: [2500, 3900],
  },
  {
    id: 43,
    width: 8,
    height: 8,
    layout: DIAMOND_HOLES_8,
    fruits: [...SIX_FRUITS],
    moves: 30,
    objective: { type: 'collect', fruit: 'watermelon', count: 32 },
    starScores: [1500, 2400],
  },
  {
    id: 44,
    width: 8,
    height: 8,
    fruits: [...SIX_FRUITS],
    moves: 28,
    objective: { type: 'score', target: 2300 },
    starScores: [3300, 5000],
  },
  {
    id: 45,
    width: 8,
    height: 8,
    layout: JELLY_RING_8,
    fruits: [...SIX_FRUITS],
    moves: 34,
    objective: { type: 'jelly' },
    starScores: [2500, 3900],
  },
  {
    id: 46,
    width: 8,
    height: 8,
    fruits: [...SIX_FRUITS],
    moves: 30,
    objective: { type: 'collect', fruit: 'mangosteen', count: 32 },
    starScores: [1500, 2400],
  },
  {
    id: 47,
    width: 8,
    height: 8,
    fruits: [...SIX_FRUITS],
    moves: 28,
    objective: { type: 'score', target: 2400 },
    starScores: [3400, 5100],
  },
  {
    id: 48,
    width: 8,
    height: 8,
    layout: JELLY_CROSS_8,
    fruits: [...SIX_FRUITS],
    moves: 34,
    objective: { type: 'jelly' },
    starScores: [2500, 4000],
  },
];
