import { startApp } from './game/app';

startApp({
  titleEl: document.getElementById('screen-title') as HTMLElement,
  mapEl: document.getElementById('screen-map') as HTMLElement,
  playEl: document.getElementById('screen-play') as HTMLElement,
  canvas: document.getElementById('board') as HTMLCanvasElement,
  hud: document.getElementById('hud') as HTMLElement,
  dialogRoot: document.getElementById('dialog-root') as HTMLElement,
});

// sw.js only exists in the production build (generated by scripts/build-sw.mjs
// after `vite build`) — registering it in dev would just 404 on every load.
if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    void navigator.serviceWorker.register('./sw.js');
  });
}
